# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: actor.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'actor.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x61\x63tor.proto\x12\x05\x61\x63tor\"6\n\x03PID\x12\x0f\n\x07\x41\x64\x64ress\x18\x01 \x01(\t\x12\n\n\x02Id\x18\x02 \x01(\t\x12\x12\n\nrequest_id\x18\x03 \x01(\r\"\x0c\n\nPoisonPill\"0\n\x12\x44\x65\x61\x64LetterResponse\x12\x1a\n\x06Target\x18\x01 \x01(\x0b\x32\n.actor.PID\"$\n\x05Watch\x12\x1b\n\x07Watcher\x18\x01 \x01(\x0b\x32\n.actor.PID\"&\n\x07Unwatch\x12\x1b\n\x07Watcher\x18\x01 \x01(\x0b\x32\n.actor.PID\"K\n\nTerminated\x12\x17\n\x03who\x18\x01 \x01(\x0b\x32\n.actor.PID\x12$\n\x03Why\x18\x02 \x01(\x0e\x32\x17.actor.TerminatedReason\"\x06\n\x04Stop\"\x07\n\x05Touch\"\"\n\x07Touched\x12\x17\n\x03who\x18\x01 \x01(\x0b\x32\n.actor.PID*D\n\x10TerminatedReason\x12\x0b\n\x07Stopped\x10\x00\x12\x15\n\x11\x41\x64\x64ressTerminated\x10\x01\x12\x0c\n\x08NotFound\x10\x02\x42)Z\'github.com/asynkron/protoactor-go/actorb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'actor_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\'github.com/asynkron/protoactor-go/actor'
  _globals['_TERMINATEDREASON']._serialized_start=350
  _globals['_TERMINATEDREASON']._serialized_end=418
  _globals['_PID']._serialized_start=22
  _globals['_PID']._serialized_end=76
  _globals['_POISONPILL']._serialized_start=78
  _globals['_POISONPILL']._serialized_end=90
  _globals['_DEADLETTERRESPONSE']._serialized_start=92
  _globals['_DEADLETTERRESPONSE']._serialized_end=140
  _globals['_WATCH']._serialized_start=142
  _globals['_WATCH']._serialized_end=178
  _globals['_UNWATCH']._serialized_start=180
  _globals['_UNWATCH']._serialized_end=218
  _globals['_TERMINATED']._serialized_start=220
  _globals['_TERMINATED']._serialized_end=295
  _globals['_STOP']._serialized_start=297
  _globals['_STOP']._serialized_end=303
  _globals['_TOUCH']._serialized_start=305
  _globals['_TOUCH']._serialized_end=312
  _globals['_TOUCHED']._serialized_start=314
  _globals['_TOUCHED']._serialized_end=348
# @@protoc_insertion_point(module_scope)
