# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: platform.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'platform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import actor_pb2 as actor__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplatform.proto\x12\x05proto\x1a\x0b\x61\x63tor.proto\"/\n\x08StoreRef\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x17\n\x03PID\x18\x02 \x01(\x0b\x32\n.actor.PID\"O\n\x08\x41\x63torRef\x12\x1e\n\x05Store\x18\x01 \x01(\x0b\x32\x0f.proto.StoreRef\x12\n\n\x02ID\x18\x02 \x01(\t\x12\x17\n\x03PID\x18\x03 \x01(\x0b\x32\n.actor.PID\"S\n\tActorInfo\x12\x1c\n\x03Ref\x18\x01 \x01(\x0b\x32\x0f.proto.ActorRef\x12\x13\n\x0b\x43\x61lcLatency\x18\x02 \x01(\x03\x12\x13\n\x0bLinkLatency\x18\x03 \x01(\x03\"3\n\x04\x46low\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x1f\n\x06Source\x18\x02 \x01(\x0b\x32\x0f.proto.StoreRef\"}\n\rEncodedObject\x12\n\n\x02ID\x18\x01 \x01(\t\x12\x0c\n\x04\x44\x61ta\x18\x02 \x01(\x0c\x12\x1f\n\x06Source\x18\x03 \x01(\x0b\x32\x0f.proto.StoreRef\x12!\n\x08Language\x18\x04 \x01(\x0e\x32\x0f.proto.Language\x12\x0e\n\x06Stream\x18\x05 \x01(\x08\"p\n\x0bStreamChunk\x12\x10\n\x08StreamID\x18\x01 \x01(\t\x12\x0e\n\x06Target\x18\x02 \x01(\t\x12\x0b\n\x03\x45oS\x18\x03 \x01(\x08\x12#\n\x05Value\x18\x04 \x01(\x0b\x32\x14.proto.EncodedObject\x12\r\n\x05\x45rror\x18\x05 \x01(\t\"V\n\x06Invoke\x12\x0e\n\x06Target\x18\x01 \x01(\t\x12\x11\n\tSessionID\x18\x02 \x01(\t\x12\r\n\x05Param\x18\x03 \x01(\t\x12\x1a\n\x05Value\x18\x04 \x01(\x0b\x32\x0b.proto.Flow\"Q\n\x0bInvokeStart\x12\x1e\n\x04Info\x18\x01 \x01(\x0b\x32\x10.proto.ActorInfo\x12\x11\n\tSessionID\x18\x02 \x01(\t\x12\x0f\n\x07ReplyTo\x18\x03 \x01(\t\"\x7f\n\x0eInvokeResponse\x12\x0e\n\x06Target\x18\x01 \x01(\t\x12\x11\n\tSessionID\x18\x02 \x01(\t\x12\x1b\n\x06Result\x18\x03 \x01(\x0b\x32\x0b.proto.Flow\x12\r\n\x05\x45rror\x18\x04 \x01(\t\x12\x1e\n\x04Info\x18\x05 \x01(\x0b\x32\x10.proto.ActorInfo*I\n\x08Language\x12\x10\n\x0cLANG_UNKNOWN\x10\x00\x12\r\n\tLANG_JSON\x10\x01\x12\x0b\n\x07LANG_GO\x10\x02\x12\x0f\n\x0bLANG_PYTHON\x10\x03\x42 Z\x1egithub.com/9triver/ignis/protob\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z\036github.com/9triver/ignis/proto'
  _globals['_LANGUAGE']._serialized_start=847
  _globals['_LANGUAGE']._serialized_end=920
  _globals['_STOREREF']._serialized_start=38
  _globals['_STOREREF']._serialized_end=85
  _globals['_ACTORREF']._serialized_start=87
  _globals['_ACTORREF']._serialized_end=166
  _globals['_ACTORINFO']._serialized_start=168
  _globals['_ACTORINFO']._serialized_end=251
  _globals['_FLOW']._serialized_start=253
  _globals['_FLOW']._serialized_end=304
  _globals['_ENCODEDOBJECT']._serialized_start=306
  _globals['_ENCODEDOBJECT']._serialized_end=431
  _globals['_STREAMCHUNK']._serialized_start=433
  _globals['_STREAMCHUNK']._serialized_end=545
  _globals['_INVOKE']._serialized_start=547
  _globals['_INVOKE']._serialized_end=633
  _globals['_INVOKESTART']._serialized_start=635
  _globals['_INVOKESTART']._serialized_end=716
  _globals['_INVOKERESPONSE']._serialized_start=718
  _globals['_INVOKERESPONSE']._serialized_end=845
# @@protoc_insertion_point(module_scope)
