# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster/cluster.proto
# Protobuf Python Version: 5.29.0
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    29,
    0,
    '',
    'cluster/cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import platform_pb2 as platform__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x15\x63luster/cluster.proto\x12\x05proto\x1a\x0eplatform.proto\"=\n\rObjectRequest\x12\n\n\x02ID\x18\x01 \x01(\t\x12 \n\x07ReplyTo\x18\x02 \x01(\x0b\x32\x0f.proto.StoreRef\"P\n\x0eObjectResponse\x12\n\n\x02ID\x18\x01 \x01(\t\x12#\n\x05Value\x18\x02 \x01(\x0b\x32\x14.proto.EncodedObject\x12\r\n\x05\x45rror\x18\x03 \x01(\t\"\xe2\x01\n\x08\x45nvelope\x12\x1e\n\x05Store\x18\x01 \x01(\x0b\x32\x0f.proto.StoreRef\x12 \n\x04Type\x18\x02 \x01(\x0e\x32\x12.proto.MessageType\x12-\n\rObjectRequest\x18\x03 \x01(\x0b\x32\x14.proto.ObjectRequestH\x00\x12/\n\x0eObjectResponse\x18\x04 \x01(\x0b\x32\x15.proto.ObjectResponseH\x00\x12)\n\x0bStreamChunk\x18\x05 \x01(\x0b\x32\x12.proto.StreamChunkH\x00\x42\t\n\x07Message*Y\n\x0bMessageType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x12\n\x0eOBJECT_REQUEST\x10\x01\x12\x13\n\x0fOBJECT_RESPONSE\x10\x02\x12\x10\n\x0cSTREAM_CHUNK\x10\x03\x42(Z&github.com/9triver/ignis/proto/clusterb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster.cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z&github.com/9triver/ignis/proto/cluster'
  _globals['_MESSAGETYPE']._serialized_start=422
  _globals['_MESSAGETYPE']._serialized_end=511
  _globals['_OBJECTREQUEST']._serialized_start=48
  _globals['_OBJECTREQUEST']._serialized_end=109
  _globals['_OBJECTRESPONSE']._serialized_start=111
  _globals['_OBJECTRESPONSE']._serialized_end=191
  _globals['_ENVELOPE']._serialized_start=194
  _globals['_ENVELOPE']._serialized_end=420
# @@protoc_insertion_point(module_scope)
