# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: resource/logger/logger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'resource/logger/logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import logger_pb2 as common_dot_logger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1cresource/logger/logger.proto\x12\x0fresource.logger\x1a\x13\x63ommon/logger.proto\"\x80\x01\n\x10LogStreamMessage\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12!\n\x05\x65ntry\x18\x02 \x01(\x0b\x32\x10.common.LogEntryH\x00\x12(\n\x07\x63ontrol\x18\x03 \x01(\x0b\x32\x15.common.StreamControlH\x00\x42\t\n\x07message\"s\n\x11LogStreamResponse\x12\x14\n\x0c\x63omponent_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x17\n\x0fprocessed_count\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t2h\n\rLoggerService\x12W\n\nStreamLogs\x12!.resource.logger.LogStreamMessage\x1a\".resource.logger.LogStreamResponse(\x01\x30\x01\x42:Z8github.com/9triver/iarnet/internal/proto/resource/loggerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'resource.logger.logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z8github.com/9triver/iarnet/internal/proto/resource/logger'
  _globals['_LOGSTREAMMESSAGE']._serialized_start=71
  _globals['_LOGSTREAMMESSAGE']._serialized_end=199
  _globals['_LOGSTREAMRESPONSE']._serialized_start=201
  _globals['_LOGSTREAMRESPONSE']._serialized_end=316
  _globals['_LOGGERSERVICE']._serialized_start=318
  _globals['_LOGGERSERVICE']._serialized_end=422
# @@protoc_insertion_point(module_scope)
