# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: application/logger/logger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'application/logger/logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from common import logger_pb2 as common_dot_logger__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1f\x61pplication/logger/logger.proto\x12\x12\x61pplication.logger\x1a\x13\x63ommon/logger.proto\"K\n\x10LogStreamMessage\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x1f\n\x05\x65ntry\x18\x02 \x01(\x0b\x32\x10.common.LogEntry\"u\n\x11LogStreamResponse\x12\x16\n\x0e\x61pplication_id\x18\x01 \x01(\t\x12\x0f\n\x07success\x18\x02 \x01(\x08\x12\r\n\x05\x65rror\x18\x03 \x01(\t\x12\x17\n\x0fprocessed_count\x18\x04 \x01(\x05\x12\x0f\n\x07message\x18\x05 \x01(\t2n\n\rLoggerService\x12]\n\nStreamLogs\x12$.application.logger.LogStreamMessage\x1a%.application.logger.LogStreamResponse(\x01\x30\x01\x42=Z;github.com/9triver/iarnet/internal/proto/application/loggerb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'application.logger.logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z;github.com/9triver/iarnet/internal/proto/application/logger'
  _globals['_LOGSTREAMMESSAGE']._serialized_start=76
  _globals['_LOGSTREAMMESSAGE']._serialized_end=151
  _globals['_LOGSTREAMRESPONSE']._serialized_start=153
  _globals['_LOGSTREAMRESPONSE']._serialized_end=270
  _globals['_LOGGERSERVICE']._serialized_start=272
  _globals['_LOGGERSERVICE']._serialized_end=382
# @@protoc_insertion_point(module_scope)
