# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import logger_pb2 as logger__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in logger_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class LoggerServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.SubmitLog = channel.unary_unary(
                '/logger.LoggerService/SubmitLog',
                request_serializer=logger__pb2.SubmitLogRequest.SerializeToString,
                response_deserializer=logger__pb2.SubmitLogResponse.FromString,
                _registered_method=True)
        self.SubmitLogBatch = channel.unary_unary(
                '/logger.LoggerService/SubmitLogBatch',
                request_serializer=logger__pb2.BatchSubmitLogRequest.SerializeToString,
                response_deserializer=logger__pb2.BatchSubmitLogResponse.FromString,
                _registered_method=True)
        self.StreamLogs = channel.stream_stream(
                '/logger.LoggerService/StreamLogs',
                request_serializer=logger__pb2.LogStreamMessage.SerializeToString,
                response_deserializer=logger__pb2.LogStreamResponse.FromString,
                _registered_method=True)


class LoggerServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def SubmitLog(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def SubmitLogBatch(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StreamLogs(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_LoggerServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'SubmitLog': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitLog,
                    request_deserializer=logger__pb2.SubmitLogRequest.FromString,
                    response_serializer=logger__pb2.SubmitLogResponse.SerializeToString,
            ),
            'SubmitLogBatch': grpc.unary_unary_rpc_method_handler(
                    servicer.SubmitLogBatch,
                    request_deserializer=logger__pb2.BatchSubmitLogRequest.FromString,
                    response_serializer=logger__pb2.BatchSubmitLogResponse.SerializeToString,
            ),
            'StreamLogs': grpc.stream_stream_rpc_method_handler(
                    servicer.StreamLogs,
                    request_deserializer=logger__pb2.LogStreamMessage.FromString,
                    response_serializer=logger__pb2.LogStreamResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'logger.LoggerService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('logger.LoggerService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class LoggerService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def SubmitLog(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.LoggerService/SubmitLog',
            logger__pb2.SubmitLogRequest.SerializeToString,
            logger__pb2.SubmitLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def SubmitLogBatch(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/logger.LoggerService/SubmitLogBatch',
            logger__pb2.BatchSubmitLogRequest.SerializeToString,
            logger__pb2.BatchSubmitLogResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def StreamLogs(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/logger.LoggerService/StreamLogs',
            logger__pb2.LogStreamMessage.SerializeToString,
            logger__pb2.LogStreamResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
