# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: common/logger.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'common/logger.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x13\x63ommon/logger.proto\x12\x06\x63ommon\"&\n\x08LogField\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t\":\n\nCallerInfo\x12\x0c\n\x04\x66ile\x18\x01 \x01(\t\x12\x0c\n\x04line\x18\x02 \x01(\x05\x12\x10\n\x08\x66unction\x18\x03 \x01(\t\"\x95\x01\n\x08LogEntry\x12\x11\n\ttimestamp\x18\x01 \x01(\x03\x12\x1f\n\x05level\x18\x02 \x01(\x0e\x32\x10.common.LogLevel\x12\x0f\n\x07message\x18\x03 \x01(\t\x12 \n\x06\x66ields\x18\x04 \x03(\x0b\x32\x10.common.LogField\x12\"\n\x06\x63\x61ller\x18\x05 \x01(\x0b\x32\x12.common.CallerInfo\"\x89\x02\n\rStreamControl\x12/\n\x04type\x18\x01 \x01(\x0e\x32!.common.StreamControl.ControlType\x12\x35\n\x08metadata\x18\x02 \x03(\x0b\x32#.common.StreamControl.MetadataEntry\x1a/\n\rMetadataEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\t:\x02\x38\x01\"_\n\x0b\x43ontrolType\x12\x13\n\x0f\x43ONTROL_UNKNOWN\x10\x00\x12\x15\n\x11\x43ONTROL_HEARTBEAT\x10\x01\x12\x11\n\rCONTROL_FLUSH\x10\x02\x12\x11\n\rCONTROL_CLOSE\x10\x03*\xb2\x01\n\x08LogLevel\x12\x15\n\x11LOG_LEVEL_UNKNOWN\x10\x00\x12\x13\n\x0fLOG_LEVEL_TRACE\x10\x01\x12\x13\n\x0fLOG_LEVEL_DEBUG\x10\x02\x12\x12\n\x0eLOG_LEVEL_INFO\x10\x03\x12\x12\n\x0eLOG_LEVEL_WARN\x10\x04\x12\x13\n\x0fLOG_LEVEL_ERROR\x10\x05\x12\x13\n\x0fLOG_LEVEL_FATAL\x10\x06\x12\x13\n\x0fLOG_LEVEL_PANIC\x10\x07\x42\x31Z/github.com/9triver/iarnet/internal/proto/commonb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'common.logger_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  _globals['DESCRIPTOR']._loaded_options = None
  _globals['DESCRIPTOR']._serialized_options = b'Z/github.com/9triver/iarnet/internal/proto/common'
  _globals['_STREAMCONTROL_METADATAENTRY']._loaded_options = None
  _globals['_STREAMCONTROL_METADATAENTRY']._serialized_options = b'8\001'
  _globals['_LOGLEVEL']._serialized_start=552
  _globals['_LOGLEVEL']._serialized_end=730
  _globals['_LOGFIELD']._serialized_start=31
  _globals['_LOGFIELD']._serialized_end=69
  _globals['_CALLERINFO']._serialized_start=71
  _globals['_CALLERINFO']._serialized_end=129
  _globals['_LOGENTRY']._serialized_start=132
  _globals['_LOGENTRY']._serialized_end=281
  _globals['_STREAMCONTROL']._serialized_start=284
  _globals['_STREAMCONTROL']._serialized_end=549
  _globals['_STREAMCONTROL_METADATAENTRY']._serialized_start=405
  _globals['_STREAMCONTROL_METADATAENTRY']._serialized_end=452
  _globals['_STREAMCONTROL_CONTROLTYPE']._serialized_start=454
  _globals['_STREAMCONTROL_CONTROLTYPE']._serialized_end=549
# @@protoc_insertion_point(module_scope)
