# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x07\x63luster\"\x14\n\x03\x41\x63k\x12\r\n\x05\x65rror\x18\x01 \x01(\t\"O\n\tAddWorker\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x13\n\x0bworker_rank\x18\x04 \x01(\x05\"!\n\x0cRemoveWorker\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\xaf\x01\n\x07Message\x12\"\n\x04type\x18\x01 \x01(\x0e\x32\x14.cluster.MessageType\x12\x1b\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\x0c.cluster.AckH\x00\x12(\n\nadd_worker\x18\x03 \x01(\x0b\x32\x12.cluster.AddWorkerH\x00\x12.\n\rremove_worker\x18\x04 \x01(\x0b\x32\x15.cluster.RemoveWorkerH\x00\x42\t\n\x07Message*J\n\x0bMessageType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x0e\n\nADD_WORKER\x10\x02\x12\x11\n\rREMOVE_WORKER\x10\x03\x32\x45\n\x0e\x43lusterService\x12\x33\n\x07Session\x12\x10.cluster.Message\x1a\x10.cluster.Message\"\x00(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=342
  _globals['_MESSAGETYPE']._serialized_end=416
  _globals['_ACK']._serialized_start=26
  _globals['_ACK']._serialized_end=46
  _globals['_ADDWORKER']._serialized_start=48
  _globals['_ADDWORKER']._serialized_end=127
  _globals['_REMOVEWORKER']._serialized_start=129
  _globals['_REMOVEWORKER']._serialized_end=162
  _globals['_MESSAGE']._serialized_start=165
  _globals['_MESSAGE']._serialized_end=340
  _globals['_CLUSTERSERVICE']._serialized_start=418
  _globals['_CLUSTERSERVICE']._serialized_end=487
# @@protoc_insertion_point(module_scope)
