# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: cluster.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'cluster.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rcluster.proto\x12\x07\x63luster\"%\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"O\n\tAddWorker\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12\x0c\n\x04host\x18\x02 \x01(\t\x12\x0c\n\x04port\x18\x03 \x01(\x05\x12\x13\n\x0bworker_rank\x18\x04 \x01(\x05\"!\n\x0cRemoveWorker\x12\x11\n\tworker_id\x18\x01 \x01(\t\"\x13\n\x11GetWorkersRequest\"9\n\x12GetWorkersResponse\x12#\n\x07workers\x18\x01 \x03(\x0b\x32\x12.cluster.AddWorker2\xcf\x01\n\x0e\x43lusterService\x12\x36\n\x10\x41\x64\x64WorkerCommand\x12\x12.cluster.AddWorker\x1a\x0c.cluster.Ack\"\x00\x12<\n\x13RemoveWorkerCommand\x12\x15.cluster.RemoveWorker\x1a\x0c.cluster.Ack\"\x00\x12G\n\nGetWorkers\x12\x1a.cluster.GetWorkersRequest\x1a\x1b.cluster.GetWorkersResponse\"\x00\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'cluster_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_ACK']._serialized_start=26
  _globals['_ACK']._serialized_end=63
  _globals['_ADDWORKER']._serialized_start=65
  _globals['_ADDWORKER']._serialized_end=144
  _globals['_REMOVEWORKER']._serialized_start=146
  _globals['_REMOVEWORKER']._serialized_end=179
  _globals['_GETWORKERSREQUEST']._serialized_start=181
  _globals['_GETWORKERSREQUEST']._serialized_end=200
  _globals['_GETWORKERSRESPONSE']._serialized_start=202
  _globals['_GETWORKERSRESPONSE']._serialized_end=259
  _globals['_CLUSTERSERVICE']._serialized_start=262
  _globals['_CLUSTERSERVICE']._serialized_end=469
# @@protoc_insertion_point(module_scope)
