# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import cluster_pb2 as cluster__pb2

GRPC_GENERATED_VERSION = '1.76.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + ' but the generated code in cluster_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ClusterServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Session = channel.stream_stream(
                '/cluster.ClusterService/Session',
                request_serializer=cluster__pb2.Message.SerializeToString,
                response_deserializer=cluster__pb2.Message.FromString,
                _registered_method=True)
        self.AddWorkerCommand = channel.unary_unary(
                '/cluster.ClusterService/AddWorkerCommand',
                request_serializer=cluster__pb2.AddWorker.SerializeToString,
                response_deserializer=cluster__pb2.Ack.FromString,
                _registered_method=True)
        self.RemoveWorkerCommand = channel.unary_unary(
                '/cluster.ClusterService/RemoveWorkerCommand',
                request_serializer=cluster__pb2.RemoveWorker.SerializeToString,
                response_deserializer=cluster__pb2.Ack.FromString,
                _registered_method=True)
        self.GetWorkers = channel.unary_unary(
                '/cluster.ClusterService/GetWorkers',
                request_serializer=cluster__pb2.GetWorkersRequest.SerializeToString,
                response_deserializer=cluster__pb2.GetWorkersResponse.FromString,
                _registered_method=True)


class ClusterServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Session(self, request_iterator, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def AddWorkerCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def RemoveWorkerCommand(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetWorkers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ClusterServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Session': grpc.stream_stream_rpc_method_handler(
                    servicer.Session,
                    request_deserializer=cluster__pb2.Message.FromString,
                    response_serializer=cluster__pb2.Message.SerializeToString,
            ),
            'AddWorkerCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.AddWorkerCommand,
                    request_deserializer=cluster__pb2.AddWorker.FromString,
                    response_serializer=cluster__pb2.Ack.SerializeToString,
            ),
            'RemoveWorkerCommand': grpc.unary_unary_rpc_method_handler(
                    servicer.RemoveWorkerCommand,
                    request_deserializer=cluster__pb2.RemoveWorker.FromString,
                    response_serializer=cluster__pb2.Ack.SerializeToString,
            ),
            'GetWorkers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetWorkers,
                    request_deserializer=cluster__pb2.GetWorkersRequest.FromString,
                    response_serializer=cluster__pb2.GetWorkersResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'cluster.ClusterService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('cluster.ClusterService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ClusterService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Session(request_iterator,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.stream_stream(
            request_iterator,
            target,
            '/cluster.ClusterService/Session',
            cluster__pb2.Message.SerializeToString,
            cluster__pb2.Message.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def AddWorkerCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.ClusterService/AddWorkerCommand',
            cluster__pb2.AddWorker.SerializeToString,
            cluster__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def RemoveWorkerCommand(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.ClusterService/RemoveWorkerCommand',
            cluster__pb2.RemoveWorker.SerializeToString,
            cluster__pb2.Ack.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetWorkers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/cluster.ClusterService/GetWorkers',
            cluster__pb2.GetWorkersRequest.SerializeToString,
            cluster__pb2.GetWorkersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
