# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: platform.proto
# Protobuf Python Version: 6.31.1
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    6,
    31,
    1,
    '',
    'platform.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import controller_pb2 as controller__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0eplatform.proto\x12\x08platform\x1a\x10\x63ontroller.proto\"%\n\x03\x41\x63k\x12\x0f\n\x07message\x18\x01 \x01(\t\x12\r\n\x05\x65rror\x18\x02 \x01(\t\"S\n\rApplyToWorker\x12\x11\n\tworker_id\x18\x01 \x01(\t\x12/\n\x12\x63ontroller_message\x18\x02 \x01(\x0b\x32\x13.controller.Message\"<\n\tBroadcast\x12/\n\x12\x63ontroller_message\x18\x01 \x01(\x0b\x32\x13.controller.Message\"J\n\x0cReturnResult\x12\x31\n\x12\x63ontroller_message\x18\x01 \x01(\x0b\x32\x13.controller.MessageH\x00\x42\x07\n\x05value\"\xe6\x01\n\x07Message\x12#\n\x04type\x18\x01 \x01(\x0e\x32\x15.platform.MessageType\x12\x1c\n\x03\x61\x63k\x18\x02 \x01(\x0b\x32\r.platform.AckH\x00\x12\x32\n\x0f\x61pply_to_worker\x18\x03 \x01(\x0b\x32\x17.platform.ApplyToWorkerH\x00\x12(\n\tbroadcast\x18\x04 \x01(\x0b\x32\x13.platform.BroadcastH\x00\x12/\n\rreturn_result\x18\x05 \x01(\x0b\x32\x16.platform.ReturnResultH\x00\x42\t\n\x07Message*Z\n\x0bMessageType\x12\x0f\n\x0bUNSPECIFIED\x10\x00\x12\x07\n\x03\x41\x43K\x10\x01\x12\x13\n\x0f\x41PPLY_TO_WORKER\x10\x02\x12\r\n\tBROADCAST\x10\x03\x12\r\n\tRT_RESULT\x10\x04\x32G\n\x08Platform\x12;\n\x0fPlatformSession\x12\x11.platform.Message\x1a\x11.platform.Message(\x01\x30\x01\x62\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'platform_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_MESSAGETYPE']._serialized_start=541
  _globals['_MESSAGETYPE']._serialized_end=631
  _globals['_ACK']._serialized_start=46
  _globals['_ACK']._serialized_end=83
  _globals['_APPLYTOWORKER']._serialized_start=85
  _globals['_APPLYTOWORKER']._serialized_end=168
  _globals['_BROADCAST']._serialized_start=170
  _globals['_BROADCAST']._serialized_end=230
  _globals['_RETURNRESULT']._serialized_start=232
  _globals['_RETURNRESULT']._serialized_end=306
  _globals['_MESSAGE']._serialized_start=309
  _globals['_MESSAGE']._serialized_end=539
  _globals['_PLATFORM']._serialized_start=633
  _globals['_PLATFORM']._serialized_end=704
# @@protoc_insertion_point(module_scope)
